# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CherryBlossom.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 422)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CherryBlossomIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 511, 355))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.gridLayout_2.addWidget(self.lbl_image, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 533, 23))
        self.menubar.setObjectName("menubar")
        self.menuPicture = QtWidgets.QMenu(self.menubar)
        self.menuPicture.setObjectName("menuPicture")
        self.menuMultispectral = QtWidgets.QMenu(self.menubar)
        self.menuMultispectral.setObjectName("menuMultispectral")
        self.menuHyperspectral = QtWidgets.QMenu(self.menubar)
        self.menuHyperspectral.setObjectName("menuHyperspectral")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.aOpenNaturalPicture = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.aOpenNaturalPicture.setFont(font)
        self.aOpenNaturalPicture.setObjectName("aOpenNaturalPicture")
        self.aOpenSingleBandFromMulti = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.aOpenSingleBandFromMulti.setFont(font)
        self.aOpenSingleBandFromMulti.setObjectName("aOpenSingleBandFromMulti")
        self.aOpenRGBFromMulti = QtWidgets.QAction(MainWindow)
        self.aOpenRGBFromMulti.setObjectName("aOpenRGBFromMulti")
        self.actionRGBtoHSV = QtWidgets.QAction(MainWindow)
        self.actionRGBtoHSV.setObjectName("actionRGBtoHSV")
        self.actionNDVI = QtWidgets.QAction(MainWindow)
        self.actionNDVI.setObjectName("actionNDVI")
        self.aOpenRGBFromHyper = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.aOpenRGBFromHyper.setFont(font)
        self.aOpenRGBFromHyper.setObjectName("aOpenRGBFromHyper")
        self.menuPicture.addAction(self.aOpenNaturalPicture)
        self.menuMultispectral.addAction(self.aOpenSingleBandFromMulti)
        self.menuMultispectral.addAction(self.aOpenRGBFromMulti)
        self.menuMultispectral.addAction(self.actionRGBtoHSV)
        self.menuMultispectral.addAction(self.actionNDVI)
        self.menuHyperspectral.addAction(self.aOpenRGBFromHyper)
        self.menubar.addAction(self.menuPicture.menuAction())
        self.menubar.addAction(self.menuMultispectral.menuAction())
        self.menubar.addAction(self.menuHyperspectral.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CherryBlossom"))
        self.menuPicture.setTitle(_translate("MainWindow", "&Picture"))
        self.menuMultispectral.setTitle(_translate("MainWindow", "&Multispectral"))
        self.menuHyperspectral.setTitle(_translate("MainWindow", "&Hyperspectral"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.aOpenNaturalPicture.setText(_translate("MainWindow", "Open"))
        self.aOpenSingleBandFromMulti.setText(_translate("MainWindow", "OpenSingleBand"))
        self.aOpenRGBFromMulti.setText(_translate("MainWindow", "OpenRGB"))
        self.actionRGBtoHSV.setText(_translate("MainWindow", "RGBtoHSV"))
        self.actionNDVI.setText(_translate("MainWindow", "NDVI"))
        self.aOpenRGBFromHyper.setText(_translate("MainWindow", "OpenRGB"))
