import numpy as np
a = np.array([1,2,3,4,5])
b = np.arange(1,26).reshape(5,5)
c = np.array([[1,2,4],[0,1,2],[1,0,1]])
b_trace = np.trace(b)
c_inv = np.linalg.inv(c)
print('一维数组a:' + str(a))
print('二维矩阵b:')
print(b)
print('二维矩阵b的迹'+ str(b_trace))
print('二维矩阵c:')
print(c)
print('矩阵c的逆：')
print(c_inv)
